import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Providers from "./providers";
import NavBar from "./components/NavBar/NavBar";
import { ReduxProvider } from "./store/provider";
import  CoinBar  from "./components/CoinBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Token Trek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <ReduxProvider>
        <Providers>  
          <CoinBar/>   
        <NavBar />
          {children}
        </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
