import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";
import PageLink from "./components/links/PageLink";
import Icon from "./components/Icon/Icon";
import FormInput from "./components/Inputs/FormInput";
import CustomSelect from "./components/Inputs/CustomSelect";
import ThemeButton from "./components/Buttons/Theme/Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Token Trek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}  pt-5`}>
        <Providers>
          <nav className="font-medium container flex items-center justify-between mx-auto mb-4">
            <ul className=" text-1xl flex">
              <li>
                <PageLink id="coinsLink" href="/" text="Coins" />
              </li>
              <li>
                <PageLink
                  id="portfolioLink"
                  href="../pages/Portfolio"
                  text="Portfolio"
                />
              </li>
            </ul>

            <form className=" flex gap-5" action="">
              <div className="relative flex items-center">
                <Icon
                  className="text-xl absolute ml-2.5"
                  iconVariant="search"
                />
                <FormInput
                  label="Search"
                  id="search"
                  type="text"
                  name="search"
                  placeholder="Search"
                />
              </div>

              <CustomSelect />
              <ThemeButton />
            </form>
          </nav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
